// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgFZl_fyLJ3tipLOPgq_mbc6cngD9oL6k',
    appId: '1:16069931272:web:aadd81431825240c3f3cbd',
    messagingSenderId: '16069931272',
    projectId: 'fruits-app-42887',
    authDomain: 'fruits-app-42887.firebaseapp.com',
    storageBucket: 'fruits-app-42887.firebasestorage.app',
    measurementId: 'G-6PY79DXSG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcTTqVPcffY33LUE7TbORgE7uhawchDsg',
    appId: '1:16069931272:android:f374f0855c2e27cd3f3cbd',
    messagingSenderId: '16069931272',
    projectId: 'fruits-app-42887',
    storageBucket: 'fruits-app-42887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdjhwQsimvHx5BGz4cRO7oJTOe96OOP5Q',
    appId: '1:16069931272:ios:4ec81a8aedda32b93f3cbd',
    messagingSenderId: '16069931272',
    projectId: 'fruits-app-42887',
    storageBucket: 'fruits-app-42887.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdjhwQsimvHx5BGz4cRO7oJTOe96OOP5Q',
    appId: '1:16069931272:ios:4ec81a8aedda32b93f3cbd',
    messagingSenderId: '16069931272',
    projectId: 'fruits-app-42887',
    storageBucket: 'fruits-app-42887.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgFZl_fyLJ3tipLOPgq_mbc6cngD9oL6k',
    appId: '1:16069931272:web:63f9166ce34e681f3f3cbd',
    messagingSenderId: '16069931272',
    projectId: 'fruits-app-42887',
    authDomain: 'fruits-app-42887.firebaseapp.com',
    storageBucket: 'fruits-app-42887.firebasestorage.app',
    measurementId: 'G-ZCDYCFN31T',
  );
}
